### ISSUE TITLE
http://openal.org doesn't redirect to https://openal.org

### ISSUE THREAD

**Issue by Benjamin-Loison** [NuclearMonster/openal-website#10]
While http://openal.org is returning the website content.

**Comment by NuclearMonster** [comment]
Sorry, I don't see the issue with this one?

**Comment by Benjamin-Loison** [comment]
I'm not an expert with [HTTPS](https://en.wikipedia.org/wiki/HTTPS) and [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security). [There are binaries on the website](https://openal.org/downloads/) which could to some extent (see below) be maliciously modified by a [man-in-the-middle](https://en.wikipedia.org/wiki/Man-in-the-middle_attack) involving the execution of arbitrary code on the downloader and executor computer. For instance just naively typing `openal.org` in the URL bar of a modern web-browser such as Chromium make us retrieve the content of the webpage with the unencrypted [HTTP](https://en.wikipedia.org/wiki/HTTP) protocol.

By denying serving HTTP content and properly redirecting HTTP requests to HTTPS and properly configuring HSTS, then after the first visit of a visitor on the website, he won't be attackable anymore by a man-in-the-middle (*The protection only applies after a user has visited the site at least once, relying on the principle of "[trust on first use](https://en.wikipedia.org/wiki/Trust_on_first_use)".*).

**Comment by NuclearMonster** [comment]
The functionality seems to be the same as icculus.org so at this time I don't believe we will change OpenAL.org to redirect to https but it's a good thing to double check so thank you for the report.
