### ISSUE TITLE
GPT chat does not allow editing sessions within this chat, this leads to memory overflow and the number of allowed characters and, accordingly, to breakdowns and failures in communication

### ISSUE THREAD

**Issue by LeoDanko** [NuclearMonster/openal-website#11]
GPT chat does not allow editing sessions within this chat, this leads to memory overflow and the number of allowed characters and, accordingly, to breakdowns and failures in communication. 
overflowing the chat with information that is no longer relevant leads to an extra load on system resources and, accordingly, negatively affects the number of users in the system at the same time, as it limits the chat’s ability to communicate with them

**Comment by NuclearMonster** [comment]
I think maybe you're either a spambot or looking for openaI this is for openaL.
