### ISSUE TITLE
OpenAL 2.1.0.0 version [UPDATE]

### ISSUE THREAD

**Issue by megapro17** [NuclearMonster/openal-website#4]
http://rgho.st/7TGdH44zD

Site version is 2.0.7.0.
You can check digital signature is "Creative Labs Inc", same as website
And please don't pack exe in zip on site.

**Comment by NuclearMonster** [comment]
Thanks for the suggestion, we aren't going to use a binary that we can't verify the source of. I think using a zip file on the website works out for many people for whom a proxy or firewall would block an exe directly.

**Comment by megapro17** [comment]
Omg, file source is CREATIVE LABS. C O M P A N Y. Do you ever know what is a digital signature? Stop spreading outdated version.
